'use client';

import React from 'react';
import { Info } from 'lucide-react';

export interface ReliabilityBadgeProps {
  reliability?: 'high' | 'standard' | 'reduced';
  modelTier?: 'primary' | 'fallback_1' | 'fallback_2';
  modelDisplayName?: string;
  style?: React.CSSProperties;
}

/**
 * Neutral reliability badge displayed inside AI response bubbles.
 * Appears ONLY when the response was generated by a fallback model (never for primary).
 * Informs the fallback level and model name in a clean, neutral style using the design system.
 */
export function ReliabilityBadge({
  reliability,
  modelTier,
  modelDisplayName,
  style,
}: ReliabilityBadgeProps) {
  // Rule: Do not display any badge if response came from the primary model
  if (reliability === 'high' || modelTier === 'primary' || !reliability) {
    return null;
  }

  const isFallback1 = reliability === 'standard' || modelTier === 'fallback_1';
  const isFallback2 = reliability === 'reduced' || modelTier === 'fallback_2';

  if (!isFallback1 && !isFallback2) {
    return null;
  }

  const tierLabel = isFallback1 ? 'Fallback 1' : 'Fallback 2';
  const defaultModelName = isFallback1 ? 'Gemini 3.5 Flash-Lite' : 'Gemini 3 Flash Preview';
  const resolvedModelName = modelDisplayName || defaultModelName;

  const tooltipText = isFallback1
    ? `Resposta gerada via contingência de Nível 1 (${resolvedModelName}).`
    : `Resposta gerada via contingência de Nível 2 (${resolvedModelName}).`;

  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 'var(--spacing-min)',
        background: 'var(--color-semantic-backgroundcolor-backgrounddimmer)',
        border: 'var(--strokewidth-min) solid var(--color-primitive-greyblue-greyblue-300)',
        color: 'var(--color-semantic-text-textdark)',
        padding: '2px var(--spacing-sm)',
        borderRadius: 'var(--radius-radius-full)',
        fontSize: 'var(--typography-fontsizes-caption)',
        fontWeight: 'var(--typography-fontweights-semibold)',
        fontFamily: 'var(--typography-fontfamilies-mainsans)',
        lineHeight: 'var(--typography-lineheights-body-caption)',
        ...style,
      }}
      title={tooltipText}
    >
      <Info size={12} style={{ flexShrink: 0, color: 'var(--color-semantic-text-textdark)' }} />
      {tierLabel} • {resolvedModelName}
    </span>
  );
}
