'use client';

import React from 'react';
import { Info, AlertTriangle } from 'lucide-react';

export interface ReliabilityBadgeProps {
  reliability?: 'high' | 'standard' | 'reduced';
  modelTier?: 'primary' | 'fallback_1' | 'fallback_2';
  style?: React.CSSProperties;
}

/**
 * Subtle reliability badge displayed inside AI response bubbles.
 * Appears ONLY when the response was generated by a fallback model (never for primary).
 * Designed using soft, non-alarming clinical tokens (neutral / amber).
 */
export function ReliabilityBadge({ reliability, modelTier, style }: ReliabilityBadgeProps) {
  // Rule: Do not display any badge if response came from the primary model
  if (reliability === 'high' || modelTier === 'primary' || !reliability) {
    return null;
  }

  if (reliability === 'standard' || modelTier === 'fallback_1') {
    return (
      <span
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          background: 'var(--color-primitive-mutedblue-muted-200)',
          border: '1px solid var(--color-primitive-greyblue-greyblue-300)',
          color: 'var(--color-primitive-darkblue-darkblue-400)',
          padding: '2px 8px',
          borderRadius: '9999px',
          fontSize: '11px',
          fontWeight: 600,
          fontFamily: 'var(--typography-fontfamilies-mainsans)',
          letterSpacing: '-0.2px',
          ...style,
        }}
        title="Esta resposta foi gerada pelo modelo de contingência padrão do sistema."
      >
        <Info size={12} />
        Confiabilidade padrão
      </span>
    );
  }

  if (reliability === 'reduced' || modelTier === 'fallback_2') {
    return (
      <span
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          background: '#fff8eb',
          border: '1px solid #f0cb82',
          color: 'var(--color-primitive-general-warning-3, #966115)',
          padding: '2px 8px',
          borderRadius: '9999px',
          fontSize: '11px',
          fontWeight: 600,
          fontFamily: 'var(--typography-fontfamilies-mainsans)',
          letterSpacing: '-0.2px',
          ...style,
        }}
        title="Esta resposta foi gerada por um modelo de contingência rápida devido a alta demanda."
      >
        <AlertTriangle size={12} />
        Confiabilidade reduzida
      </span>
    );
  }

  return null;
}
